export default [
    {
        id:1,
        name:"hover",
        path:"hover"  
    },
    {
        id:2,
        name:"click",
        path:"click"  
    },
    {
        id:3,
        name:"cascading",
        path:"cascading"  
    },
    {
        id:4,
        name:"sidenav",
        path:"sidenav"  
    },
    {
        id:5,
        name:"dropup",
        path:"dropup"
    }
]